version: 2

registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.REPO_GITHUB_TOKEN}}

updates:
  # npm
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - github
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "node"
        versions: ["<18.0.0", ">=19.0.0"]
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"

  # github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
